### ISSUE TITLE
Can't change information

### ISSUE THREAD

**Issue by fredrikwik** [SuperOffice/node-express-convert-certs-and-sys-token#12]
Hi, 

I do now have a weebhook that have got "stopped" (for some reason I do not know why.) 

And then when I see that it has gotten from "avtive" to "stopped" I do click edit and then changes the status to "active" and press save. 

BUT then nothing happens... 

I got this issue before as well but at that point the status was "to many errors".
I can't edit that.(or in other words, I can edit the accual field but nothing happens, it's like my "press save" do not work.

Same thing also when I tried to change the URL from the current URL to anotherone.. (did not save either)

Before:
<img width="1022" alt="Screenshot 2022-02-18 at 09 18 40" src="https://user-images.githubusercontent.com/35043772/154645555-704e12e8-67fd-4220-a7b2-7925959e991b.png">

Inside after my edit of status and then I press save:
<img width="548" alt="Screenshot 2022-02-18 at 09 19 06" src="https://user-images.githubusercontent.com/35043772/154645470-35a34f9b-b9e6-4e1e-bf0e-45c29be74361.png">

After, still the same:
<img width="1022" alt="Screenshot 2022-02-18 at 09 18 40" src="https://user-images.githubusercontent.com/35043772/154645555-704e12e8-67fd-4220-a7b2-7925959e991b.png">

**Comment by SuperOfficeDevNet** [comment]
Hi Fredrik,

That's because your webhook URL does not return a 200 status code. Instead, when I send a POST request to that endpoint, I get a 404, which after several failed attempts SuperOffice automatically flags as TooManyErrors, which also stops the webhook hook.

The specified endpoint, when saved, must exist and return a 200 status code. 

I understand your desire to use NGROK, I use to to tunnel to local websites for debugging as well, but I recommend testing creating the webhook with https://webhook.site just to get a feel for what's really happening. You will see we send out a test webhook to the endpoint to make sure it exists, and only if successful do we persist the change.

![image](https://user-images.githubusercontent.com/15157161/154649970-84ea379d-55e5-44dd-9823-4014fedf218f.png)

**Comment by SuperOfficeDevNet** [comment]
![image](https://user-images.githubusercontent.com/15157161/154651617-41305650-55cb-425b-bd4d-2603aeaff16b.png)

**Comment by fredrikwik** [comment]
Got it, thank you for the help!
